# 内部转发请求配置，0值为无超时 单位为秒
# connTimeout: 用户连接超时
# idleConnTimeout: 空闲连接超时
# responseHeaderTimeout: 响应头超时
server-conn:
  connTimeout: 0
  idleConnTimeout: 0
  responseHeaderTimeout: 0

white-addr:
   - '45.159.210.6'


# 开启特殊标记增强
flags: true

# 图片访问
domain: "https://chat-completion-chatgpt-adapter.hf.space"

# 内调llm，用于绘图时文本转tags
llm:
  baseUrl: "http://127.0.0.1:7860"
  model: "bing"
  token: "xxx"

# lmsys fn、 trigger
lmsys: [49 , 109]

# hf 绘图接口配置化
# 若旧接口不可用，可以到huggingface上查找同类型的接口配置
# 参数替换：{{prompt}}、{{negative_prompt}}、{{sampler}}、{{style}}、{{seed}}
hf:
#  animagine-xl-3.1:
#    baseUrl: https://boboiazumi-animagine-xl-3-1.hf.space
#    fn: [5, 61]
#    data: '[
#      "{{prompt}}",
#      "{{negative_prompt}}",
#      {{seed}},
#      1024,
#      1024,
#      8,
#      35,
#      "{{sampler}}",
#      "1024 x 1024",
#      "{{style}}",
#      "Standard v3.1",
#      true,
#      0.55,
#      1.5,
#      false,
#      false,
#      null,
#      0.65
#    ]'
#  dalle-4k:
#    baseUrl: https://mukaist-dalle-4k.hf.space
#  dalle-3-xl:
#    baseUrl: https://ehristoforu-dalle-3-xl-lora-v2.hf.space

# gemini 自定义安全设置
google:
#  safes:
#    - category: HARM_CATEGORY_HARASSMENT
#      threshold: BLOCK_NONE

bing:
  baseUrl: "https://edgeservices.bing.com/edgesvc"

claude:
  pad: 0
  cookies:
    - 'xxx1'
    - 'xxx2'

you:
  helper: 8082
  notice: "Creative Writing Mode"
  cookies:
    - 'daily_query_date=Fri%20Oct%2025%202024; daily_query_count=0; ab.storage.sessionId.dcee0642-d796-4a7b-9e56-a0108e133b07=g%3Aeedb5384-8085-09f3-86e0-71d1113cc82e%7Ce%3A1729852972109%7Cc%3A1729851168479%7Cl%3A1729851172109; youchat_smart_learn=true; safesearch_7ca302964bdc9906d972d6e7786dc737f9bd099b28d91e51ea36d15ae1dbe45d=Moderate; ab.storage.deviceId.dcee0642-d796-4a7b-9e56-a0108e133b07=g%3A7be381d8-acfe-ad8c-a00c-8cee3f9ca066%7Ce%3Aundefined%7Cc%3A1729851168480%7Cl%3A1729851168480; youchat_personalization=true; DSR=eyJhbGciOiJSUzI1NiIsImtpZCI6IlNLMmpJbnU3SWpjMkp1eFJad1psWHBZRUpQQkFvIiwidHlwIjoiSldUIn0.eyJhbXIiOlsiZmVkIl0sImF1dGgwSWQiOm51bGwsImRybiI6IkRTUiIsImVtYWlsIjoiSmtqYWpzRFY5Q0BleGFtcGxlLmNvbSIsImV4cCI6MTc2MTMwMDc2NywiZ2l2ZW5OYW1lIjoiIiwiaWF0IjoxNzI5ODUxMTY3LCJpc3MiOiJQMmpJbnR0Uk11WHB5WVpNYlZjc2M0QzlaMFJUIiwibGFzdE5hbWUiOiIiLCJuYW1lIjoiSmtqYWpzRFY5Q0BleGFtcGxlLmNvbSIsInBpY3R1cmUiOiIiLCJzdHl0Y2hJZCI6bnVsbCwic3ViIjoiVTJudlFlT3VBZzNEaG4wZVU0aURjTG1qV05VaSIsInRlbmFudEludml0YXRpb24iOm51bGwsInRlbmFudEludml0ZXIiOm51bGwsInVzZXJJZCI6IlUybnZRZU91QWczRGhuMGVVNGlEY0xtaldOVWkiLCJ2ZXJpZmllZEVtYWlsIjp0cnVlfQ.YiXHc_ZQwjCum1Qe0bQRrlSiGdNwmtz-qBmxei56ggFA1YMM5MnoIrVz07futSRNSwRm3ejz-b0r_4f3vYAOQhrVt34zwR7Ir6BWQaiYfiBEVrC2WFF6uUqqnQya4wKpeuV7-3K99hEvMp-Dr6stCAAs3OzP2__owtSOUJ8p_wEG0sF4cx3JX7KuIXPjprvq8-W957CRKkmBFTWTAF6RnGxO_sEVhCfcFLryc-4xRSvdS0RBD58bRnb09whLJ9bINbPdfNjo0HXRk5QxyL-kurcfuizI66bvKxi4POyVzhZrubp8aUb_D2_TrEtBX0BiWTKxmnxwHL7WI4L_Z87Rzw; ab.storage.userId.dcee0642-d796-4a7b-9e56-a0108e133b07=g%3AU2nvQeOuAg3Dhn0eU4iDcLmjWNUi%7Ce%3Aundefined%7Cc%3A1729851168478%7Cl%3A1729851168479; _gcl_au=1.1.1581807889.1729851168; ai_model=gpt_4o; DS=eyJhbGciOiJSUzI1NiIsImtpZCI6IlNLMmpJbnU3SWpjMkp1eFJad1psWHBZRUpQQkFvIiwidHlwIjoiSldUIn0.eyJhbXIiOlsiZmVkIl0sImF1dGgwSWQiOm51bGwsImRybiI6IkRTIiwiZW1haWwiOiJKa2phanNEVjlDQGV4YW1wbGUuY29tIiwiZXhwIjoxNzMyMjcwMzY3LCJnaXZlbk5hbWUiOiIiLCJpYXQiOjE3Mjk4NTExNjcsImlzcyI6IlAyakludHRSTXVYcHlZWk1iVmNzYzRDOVowUlQiLCJsYXN0TmFtZSI6IiIsIm5hbWUiOiJKa2phanNEVjlDQGV4YW1wbGUuY29tIiwicGljdHVyZSI6IiIsInJleHAiOiIyMDI1LTEwLTI0VDEwOjEyOjQ3WiIsInN0eXRjaElkIjpudWxsLCJzdWIiOiJVMm52UWVPdUFnM0RobjBlVTRpRGNMbWpXTlVpIiwidGVuYW50SW52aXRhdGlvbiI6bnVsbCwidGVuYW50SW52aXRlciI6bnVsbCwidGVuYW50cyI6eyJUZXN0U1NPIjp7fX0sInVzZXJJZCI6IlUybnZRZU91QWczRGhuMGVVNGlEY0xtaldOVWkiLCJ2ZXJpZmllZEVtYWlsIjp0cnVlfQ.ImAD-aOoUmvYzMmgfQjgBh3yD68XJ_Ylb2M-YAG58WEBfskYxCb4mzD4B0uIKrG6o0xQLygCMQOmwhiHKX9PUWbGj26YEDXZNEoK_fBYVzLkT2TlwFJY-bKmNH-ZGD6KWfr4PXIB4iep0yuaPbJGm71-Gnj4B6WE6eoVfQx_iVb2UmUqZa__Zc2V3tkv3TxKrmUwsha51SIWDfa7qr7O0DnCJZugFya3saTYsqcP9JiZYbHq8zoMpgb1J20r9QbfWidV8CuhEMJU1hKkN_HDpmrX9EEc37eEQUdLAGmgfEyni4_mCvY1JZ0FPV6mFXAvbajOO3z_zIrFkzOUlKFPVw; _cfuvid=dVTIPCLXgLDVAfWpEnMknYx4_4PugkDxPddEFc3_Bcc-1729851164845-0.0.1.1-604800000; __cf_bm=1QwYbK4ugHyFl6wfGGy85.neXnQiDV8jYGdUIplpGzA-1729851164-1.0.1.1-mpYeW92Du_E4cnzVTWQC.4jSl9vId0MWoFY3T_CYDmTAUQY_Iw_NPEYxYVZz5dxo2SqQleI1cpT0hiNBp8H.xvufUfRX.u6_fzQXoDONYqU; ld_context=%7B%22kind%22%3A%22user%22%2C%22key%22%3A%225ed82797-c303-44b4-893a-593e1c615103%22%2C%22email%22%3A%22JkjajsDV9C%40example.com%22%2C%22country%22%3A%22CN%22%2C%22userAgent%22%3A%22Mozilla%2F5.0%20(Windows%20NT%2010.0%3B%20Win64%3B%20x64)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F130.0.0.0%20Safari%2F537.36%22%2C%22secUserAgent%22%3A%22%5C%22Chromium%5C%22%3Bv%3D%5C%22130%5C%22%2C%20%5C%22Google%20Chrome%5C%22%3Bv%3D%5C%22130%5C%22%2C%20%5C%22Not%3FA_Brand%5C%22%3Bv%3D%5C%2299%5C%22%22%7D; uuid_guest_backup=5ed82797-c303-44b4-893a-593e1c615103; uuid_guest=5ed82797-c303-44b4-893a-593e1c615103; total_query_count=0; safesearch_guest=Moderate; cf_clearance=MSYT9clyQY_816ExJsVaCpsnrRnUpstzYMV7mXtp7bc-1729851166-1.2.1.1-Gpz3fqLBW3cdlT5ourHng2.fvSgUX_JuibRgDkGKoSVqzMMeQNw.uvrEdnobnvypMbpc3M5bgzi1bka3.qx9vAPTw0zxjIp3h1Jz1wbsMIYM_zeDYJ0Lcb4SULNJvUp1NMbzklr.0ywLEVCiwcCyIxZq.8FirdfmW8xrhIxEnMYD9VU4T2riCfglIvdaFFe5IZV.cotiMH4Kvdtu5Rb.nHwpvBsIv8lg.Ry6FwFbcKuyfHrITpnsbNJZU4FPQDMYQbUXZOXMEPTi7mecFm1dIUC6l_jR0ioZBy55hlrLt263mIyluYmwO2Qaz1Id0iEQq7EvDPK_RfOnQphiqXEo9eQeSOkqZ5nSRiY7H4.fUXVSAtEliItsTbTeFMy6qmIIoUjMW0yOgnqyqDBUfU0adw'
    - 'daily_query_date=Fri%20Oct%2025%202024; daily_query_count=0; ab.storage.sessionId.dcee0642-d796-4a7b-9e56-a0108e133b07=g%3A5f3a62b4-8bde-e39e-68b8-a178546d116e%7Ce%3A1729852985867%7Cc%3A1729851182972%7Cl%3A1729851185867; youchat_smart_learn=true; safesearch_a47518b90f9b94bbf97facbee245834e04bbb2a8dc53168257c6ed359c918c44=Moderate; ab.storage.deviceId.dcee0642-d796-4a7b-9e56-a0108e133b07=g%3A231b7e3f-9294-71cb-73d9-29847ffe2b3d%7Ce%3Aundefined%7Cc%3A1729851182973%7Cl%3A1729851182973; youchat_personalization=true; DSR=eyJhbGciOiJSUzI1NiIsImtpZCI6IlNLMmpJbnU3SWpjMkp1eFJad1psWHBZRUpQQkFvIiwidHlwIjoiSldUIn0.eyJhbXIiOlsiZmVkIl0sImF1dGgwSWQiOm51bGwsImRybiI6IkRTUiIsImVtYWlsIjoieDFrbzc0UGtkWkBleGFtcGxlLmNvbSIsImV4cCI6MTc2MTMwMDc4MiwiZ2l2ZW5OYW1lIjoiIiwiaWF0IjoxNzI5ODUxMTgyLCJpc3MiOiJQMmpJbnR0Uk11WHB5WVpNYlZjc2M0QzlaMFJUIiwibGFzdE5hbWUiOiIiLCJuYW1lIjoieDFrbzc0UGtkWkBleGFtcGxlLmNvbSIsInBpY3R1cmUiOiIiLCJzdHl0Y2hJZCI6bnVsbCwic3ViIjoiVTJudlFnMkQ5UG50TUFOdjhSajdNdW54VmhHZyIsInRlbmFudEludml0YXRpb24iOm51bGwsInRlbmFudEludml0ZXIiOm51bGwsInVzZXJJZCI6IlUybnZRZzJEOVBudE1BTnY4Umo3TXVueFZoR2ciLCJ2ZXJpZmllZEVtYWlsIjp0cnVlfQ.jWAlWexWnK7nQlpfthdtjrxr-QkNxLzs-gKacs4djwo06qKD0bxWkCtNQirtWf41YdwHxWZv8iTn-uyic4ETx6l3FfEpIy1diLeJBXWeph5KYchp1ekMC3aj6xKf7-1eel0XnO9Q8-n8ijYbdZrwDxkH6KXO6DedhRqHiaOakQ-J_NvIdkNDtI_6S36UlDVkeXN_VqQ-ihZUI-7_KV6AvuT5OhnBT_pt70J1ezFoN8V3hgfbPdXUR0r6v4ZNxqGFGFr1B22wAoDkOkQO8AB1KvZtJlJw9wnzPFB3FH50QFSV1Cb0wHEhInUUWsaKAqTJVAcMAaKI5hB3UwRC1bMZ6w; ab.storage.userId.dcee0642-d796-4a7b-9e56-a0108e133b07=g%3AU2nvQg2D9PntMANv8Rj7MunxVhGg%7Ce%3Aundefined%7Cc%3A1729851182972%7Cl%3A1729851182973; _gcl_au=1.1.406874309.1729851182; ai_model=gpt_4o; DS=eyJhbGciOiJSUzI1NiIsImtpZCI6IlNLMmpJbnU3SWpjMkp1eFJad1psWHBZRUpQQkFvIiwidHlwIjoiSldUIn0.eyJhbXIiOlsiZmVkIl0sImF1dGgwSWQiOm51bGwsImRybiI6IkRTIiwiZW1haWwiOiJ4MWtvNzRQa2RaQGV4YW1wbGUuY29tIiwiZXhwIjoxNzMyMjcwMzgyLCJnaXZlbk5hbWUiOiIiLCJpYXQiOjE3Mjk4NTExODIsImlzcyI6IlAyakludHRSTXVYcHlZWk1iVmNzYzRDOVowUlQiLCJsYXN0TmFtZSI6IiIsIm5hbWUiOiJ4MWtvNzRQa2RaQGV4YW1wbGUuY29tIiwicGljdHVyZSI6IiIsInJleHAiOiIyMDI1LTEwLTI0VDEwOjEzOjAyWiIsInN0eXRjaElkIjpudWxsLCJzdWIiOiJVMm52UWcyRDlQbnRNQU52OFJqN011bnhWaEdnIiwidGVuYW50SW52aXRhdGlvbiI6bnVsbCwidGVuYW50SW52aXRlciI6bnVsbCwidGVuYW50cyI6eyJUZXN0U1NPIjp7fX0sInVzZXJJZCI6IlUybnZRZzJEOVBudE1BTnY4Umo3TXVueFZoR2ciLCJ2ZXJpZmllZEVtYWlsIjp0cnVlfQ.dixs9jgbZkbRep7PrXKqQYtIFRHoSCQn8OfJB2cdu2-TJZARRWoZRJFCpDUScGuuuWX5fWDrtRuKq3Os0t8BqEl2Bps371vDYdJwSIw-eqddZPHDOZiGlw4_9uTa7lzYPY_l6F6hKe4VGTAtclnvo4-H8kUwcP87H7lKJz9z4brQo7gEOcAd0jGwErGc0yWDvxzPxtVIgcnNHsH5SSS-wWVW3F41N0Z-i1JgLqFOVirYANFghliHvONfFlxP5-uxZ74L3jffmFtLTpdCSattVTPGMbYARh3JTbE6UW0PFBX0aDYxJ7Xb3_HjJkZ8RrzN0McQqIpjRYlMiPafxnyUYw; _cfuvid=sm4qB6FUiaRigkZYa7XvxPCux7xuM8oYFsmBaagYE.M-1729851179728-0.0.1.1-604800000; __cf_bm=vtH_ZWSndFv6VcslX58ggEu9v.k.4Z8iJb0i52mibkw-1729851179-1.0.1.1-14IUq4idY.FNfCJBFFZCqivGtgroIECcM13G2aRXiIGDI4auTJxeq2.aP4LQ0XdpDcHAvfOLxMlpUgU9hi_JznR_RneZUITo7OFie77w1J8; ld_context=%7B%22kind%22%3A%22user%22%2C%22key%22%3A%22c44d7cf4-5d22-40a7-b4ca-067682ac986e%22%2C%22email%22%3A%22x1ko74PkdZ%40example.com%22%2C%22country%22%3A%22CN%22%2C%22userAgent%22%3A%22Mozilla%2F5.0%20(Windows%20NT%2010.0%3B%20Win64%3B%20x64)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F130.0.0.0%20Safari%2F537.36%22%2C%22secUserAgent%22%3A%22%5C%22Chromium%5C%22%3Bv%3D%5C%22130%5C%22%2C%20%5C%22Google%20Chrome%5C%22%3Bv%3D%5C%22130%5C%22%2C%20%5C%22Not%3FA_Brand%5C%22%3Bv%3D%5C%2299%5C%22%22%7D; uuid_guest_backup=c44d7cf4-5d22-40a7-b4ca-067682ac986e; uuid_guest=c44d7cf4-5d22-40a7-b4ca-067682ac986e; total_query_count=0; safesearch_guest=Moderate; cf_clearance=69qQrgkOVzSJZzpUoiqal5wwMQZK9jFsUSC5KquJ_IQ-1729851181-1.2.1.1-jNRX9.vtGhWKDarbF7dl4yqkW2G0X1qG8xviqsZ__cpvxZzzmlVWSVD5u3rzaeZw_a5XccsRBFoJt0bt6T4qsw.CE8pAh8C1b7pUS3yLpwtjoYd4eF_IazrpWZDXKjrnYXRjSqjmbofJVAoq2lwEjzNo34xREX_nUnokmklWG6F3JrhuFTC6hAGbBZOrtcolJJoz1zjWcAqJhEWxBnyRSCdN_3AbQXGr_sU_e4pzJ7V.fij8_Erv08as.cyXvpcAbaOJim4ovZyTE7F5JBgI9xPd7QnVv9gSoOExVGnjnDltSNCGF.6d07wWQR2_qxtACSN9d33.5cqFGQGtlASYiVWWeIJmYxITYqic8EQ441pgNGdAMkrJbxsSSHlCxlgIrPV2O1OMa7SEKd8RtdtjZw'

serverless:
  enabled: true
  disabled-gpu: true
  # 当无法找到指定的浏览器时可以在此配置路径
  # execPath: /usr/bin/microsoft-edge
  headless: new

# coze 默认配置；；；内置配置经常变动，难以维护改为配置化。新增webSdk模式，但还未得知速率是否有限制？？？
coze:
#  8k:
#    botId: 114514
#    version: 9527
#    scene: 2
#    isW: false
#  128k:
#    botId: 114514
#    version: 9527
#    scene: 2
#    isW: false
#  images:
#    botId: 114514
#    version: 9527
#    scene: 2

# 多个websdk账号可开启，用于请求计数，超过count数量该账号进入静置区
  websdk:
#    counter: 0
#    model:
#    accounts:
#    - email: xxx@gmail.com
#      password: xxx
#      validate: xxx@gmail.com

interpreter:
  baseUrl: http://127.0.0.1:7860
  echoCode: false
  ws: true

custom-llm:
  baseUrl: http://127.0.0.1:8080

# toolCall 默认配置化; 在 flags 关闭时也可用
toolCall:
  id: -1
  enabled: false
  tasks: false

# 图片放大，domain需要公网可访问的地址
# key请到https://bigjpg.com获取，每月30次免费
# 目前注册没有限制，可配置多个key轮询
#magnify:
#  - "xxx"
